version: '3'
services:
  node:
    image: shelter-node-dev
    restart: always
    build:
      context: ./node
      dockerfile: ./Dockerfile.dev
    volumes:
      - '../:/app'
    ports:
      - 8000:8000
      - 8001:8001
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DB}
    ports:
      - 5432:5432
