version: '3'
services:
  node:
    image: node
    restart: always
    build:
      context: ./node
    volumes:
      - '../:/app'
    ports:
      - 8000:8000
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DB}
