name: test-build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Project
        run: |-
          bash ./project install
      - name: Copy environment file
        run: |-
          cp .env.local .env
      - name: Build Project
        run: |-
          bash ./project app:build
